# app/context.py
TRADUCCIONES = {
    
        # Agregar en la seccion TERMINAL BIOMoTRICA
    "ESCANEANDO":                           {"en": "SCANNING"},
    "ANALIZANDO RASGOS BIOMETRICOS":        {"en": "ANALYZING BIOMETRIC FEATURES"},
    "ACCESO AUTORIZADO":                    {"en": "ACCESS AUTHORIZED"},   # ya existe
    "ACCESO DENEGADO":                      {"en": "ACCESS DENIED"},        # ya existe
    "USUARIO NO REGISTRADO":                {"en": "UNREGISTERED USER"},    # ya existe
    "MULTIPLES ROSTROS DETECTADOS":         {"en": "MULTIPLE FACES DETECTED"},
    "SOLO UN USUARIO A LA VEZ":             {"en": "ONE USER AT A TIME"},
    "SIN CAMARA":                           {"en": "NO CAMERA"},
    "NO SE DETECTO NINGUN DISPOSITIVO":     {"en": "NO DEVICE DETECTED"},
    "ACERQUESE A LA CAMARA":                {"en": "MOVE CLOSER TO THE CAMERA"},
    "ROSTRO DEMASIADO LEJOS O PEQUENO":     {"en": "FACE TOO FAR OR SMALL"},
    "MEJORE LA ILUMINACION":                {"en": "IMPROVE LIGHTING"},
    "AMBIENTE MUY OSCURO - ENCIENDA UNA LUZ": {"en": "TOO DARK - TURN ON A LIGHT"},
    "POSICIONE SU ROSTRO":                  {"en": "POSITION YOUR FACE"},
    "MIRANDO HACIA LA CAMARA":              {"en": "LOOKING AT THE CAMERA"},
    "BIENVENIDO":                           {"en": "WELCOME"},
    "ACCESO CONCEDIDO":                     {"en": "ACCESS GRANTED"},
    "REGISTRANDO BIOMETRIA":                {"en": "REGISTERING BIOMETRICS"},
    "COLOQUE SU ROSTRO FRENTE A LA CAMARA": {"en": "PLACE YOUR FACE IN FRONT OF THE CAMERA"},
    "USUARIO YA REGISTRADO":                {"en": "USER ALREADY REGISTERED"},
    "ESTE ROSTRO YA EXISTE EN EL SISTEMA":  {"en": "THIS FACE ALREADY EXISTS IN THE SYSTEM"},
    "ESPERANDO DETECCION...":               {"en": "WAITING FOR DETECTION..."},
    "Iniciando camara...":                  {"en": "Starting camera..."},
    "Sistema Biometrico v2.0":              {"en": "Biometric System v2.0"},
    "RECONOCIMIENTO FACIAL":                {"en": "FACIAL RECOGNITION"},
    "ANALIZANDO RASGOS BIOMETRICOS":        {"en": "ANALYZING BIOMETRIC FEATURES"},
    "ANALIZANDO RASGOS BIOMETRICOS":        {"en": "ANALYZING BIOMETRIC FEATURES"},

    # --------------------------------------------------------------
    # TABLA DE ACCESOS  motivos y resultados
    # --------------------------------------------------
    "Acceso denegado":              {"en": "Access denied"},
    "Usuario inactivo":             {"en": "Inactive user"},
    "Usuario no identificado":      {"en": "User not identified"},
    "AUTORIZADO":                   {"en": "AUTHORIZED"},
    "DENEGADO":                     {"en": "DENIED"},

    # Tabla de accesos  textos faltantes
    "Sin cuenta":                   {"en": "No account"},
    "Sin correo":                   {"en": "No email"},
    "USUARIO NO REGISTRADO":        {"en": "UNREGISTERED USER"},

    # Catï¿½logo usuarios ï¿½ badges de rol
    "Estudiante":                   {"en": "Student"},
    "Docente":                      {"en": "Teacher"},
    "Trabajador":                   {"en": "Worker"},
    "ESTUDIANTE":                   {"en": "STUDENT"},
    "DOCENTE":                      {"en": "TEACHER"},
    "TRABAJADOR":                   {"en": "WORKER"},

    # Catï¿½logo usuarios ï¿½ estado
    "? ACTIVO":                     {"en": "? ACTIVE"},
    "? INACTIVO":                   {"en": "? INACTIVE"},
    "ACTIVO":                       {"en": "ACTIVE"},
    "INACTIVO":                     {"en": "INACTIVE"},

     # --------------------------------------------------------------
    # NAVEGACIï¿½N / SIDEBAR
    # --------------------------------------------------------------
    "Panel de Control":                             {"en": "Control Panel"},
    "??   Panel de Control":                        {"en": "??   Control Panel"},
    "?? Panel de Control":                          {"en": "?? Control Panel"},
    "GestiÃ³n de Usuarios":                          {"en": "User Management"},
    "Gestion de Usuarios":                          {"en": "User Management"},
    "??   GestiÃ³n de Usuarios":                     {"en": "??   User Management"},
    "?? Gestion de Usuarios":                       {"en": "?? User Management"},
    "GestiÃ³n de Facultades":                        {"en": "Faculty Management"},
    "Gestion de Facultades":                        {"en": "Faculty Management"},
    "??   GestiÃ³n de Facultades":                   {"en": "??   Faculty Management"},
    "?? Gestion de Facultades":                     {"en": "?? Faculty Management"},
    "GestiÃ³n de Carreras":                          {"en": "Career Management"},
    "Gestion de Carreras":                          {"en": "Career Management"},
    "??   GestiÃ³n de Carreras":                     {"en": "??   Career Management"},
    "?? Gestion de Carreras":                       {"en": "?? Career Management"},
    "ConfiguraciÃ³n":                                {"en": "Settings"},
    "ConfiguraciÃ³n Cuenta":                         {"en": "Account Settings"},
    "??   ConfiguraciÃ³n Cuenta":                    {"en": "??   Account Settings"},
    "?? ConfiguraciÃ³n Cuenta":                      {"en": "?? Account Settings"},
    "Cerrar SesiÃ³n":                                {"en": "Log Out"},
    "?? Cerrar SesiÃ³n":                             {"en": "?? Log Out"},
    "ADMINISTRADOR":                                {"en": "ADMINISTRATOR"},
    "Control BiomÃ©trico":                           {"en": "Biometric Control"},

    # --------------------------------------------------------------
    # DASHBOARD ï¿½ encabezado y stats
    # --------------------------------------------------------------
    "??  Panel de Control":                         {"en": "??  Control Panel"},
    "Resumen general y actividad reciente":         {"en": "General summary and recent activity"},
    "Total Registros":                              {"en": "Total Records"},
    "Accesos Hoy":                                  {"en": "Today's Access"},
    "Autorizados":                                  {"en": "Authorized"},
    "Denegados":                                    {"en": "Denied"},

    # DASHBOARD ï¿½ grï¿½fica
    "?? Tendencia de Accesos por Hora":             {"en": "?? Access Trend by Hour"},
    "Fecha:":                                       {"en": "Date:"},
    "Accesos por hora":                             {"en": "Access by hour"},
    "Sin accesos registrados en esta fecha":        {"en": "No access records for this date"},

    # DASHBOARD ï¿½ tabla ï¿½ltimos accesos
    "Registro de Ãºltimos accesos":                  {"en": "Latest access log"},
    "Sin accesos registrados":                      {"en": "No access records found"},

    # DASHBOARD ï¿½ filtro roles
    "?? Rol:":                                      {"en": "?? Role:"},
    "Todos":                                        {"en": "All"},
    "?? Filtrar ?":                                 {"en": "?? Filter ?"},
    "?? Filtrar ?":                                 {"en": "?? Filter ?"},
    "Filtrar ?":                                    {"en": "Filter ?"},
    "Filtrar ?":                                    {"en": "Filter ?"},


    # --------------------------------------------------------------
    # GESTIï¿½N DE USUARIOS ï¿½ tabla
    # --------------------------------------------------------------
    "?? GestiÃ³n de Usuarios":                       {"en": "?? User Management"},
    "Agregar Usuario":                              {"en": "Add User"},
    "? Agregar Usuario":                           {"en": "? Add User"},
    "Buscar usuario...":                            {"en": "Search user..."},
    "No hay usuarios registrados":                  {"en": "No registered users"},
    "FOTOGRAFA":                                   {"en": "PHOTO"},
    "INFORMACIÃ“N":                                  {"en": "INFORMATION"},
    "ESTADO":                                       {"en": "STATUS"},
    "ACCIONES":                                     {"en": "ACTIONS"},

    # GESTIï¿½N DE USUARIOS ï¿½ formulario secciones
    "Editar Registro":                              {"en": "Edit Record"},
    "?? Editar Registro":                           {"en": "?? Edit Record"},
    "Nuevo Registro":                               {"en": "New Record"},
    "? Nuevo Registro":                            {"en": "? New Record"},
    "?? InformaciÃ³n Personal":                      {"en": "?? Personal Information"},
    "InformaciÃ³n Personal":                         {"en": "Personal Information"},
    "?? IdentificaciÃ³n":                            {"en": "?? Identification"},
    "IdentificaciÃ³n":                               {"en": "Identification"},
    "?? Estado del usuario":                        {"en": "?? User Status"},
    "Usuario activo":                               {"en": "Active user"},

    # GESTIï¿½N DE USUARIOS ï¿½ labels de campos
    "Nombres":                                      {"en": "First Name(s)"},
    "Apellido Paterno":                             {"en": "Last Name"},
    "Apellido Materno":                             {"en": "Second Last Name"},
    "cuenta":                                       {"en": "account"},
    "correo":                                       {"en": "email"},

    # GESTIï¿½N DE USUARIOS ï¿½ biometrï¿½a
    "Registrar BiometrÃ­a":                          {"en": "Register Biometrics"},
    "?? Registrar BiometrÃ­a":                       {"en": "?? Register Biometrics"},
    "Abriendo cÃ¡mara...":                           {"en": "Opening camera..."},
    "?? Abriendo cÃ¡mara...":                        {"en": "?? Opening camera..."},
    "BiometrÃ­a registrada":                         {"en": "Biometrics registered"},
    "? BiometrÃ­a registrada":                       {"en": "? Biometrics registered"},
    "BiometrÃ­a requerida":                          {"en": "Biometrics required"},
    "? BiometrÃ­a requerida":                        {"en": "? Biometrics required"},
    "Corrige los datos primero":                    {"en": "Fix the data first"},
    "? Corrige los datos primero":                  {"en": "? Fix the data first"},

    # GESTIï¿½N DE USUARIOS ï¿½ modal
    "ðŸ—‘ï¸Desactivar este usuario?":                    {"en": "Desactivate this user?"},
    "El usuario perderÃ¡ acceso al sistema.":        {"en": "The user will lose system access."},
    "Desactivar":                                   {"en": "Desactivate"},
    "??? Desactivar":                                {"en": "??? Desactivate"},
    "ðŸ”„Activar este usuario?":                       {"en": "Activate this user?"},
    "El usuario recuperarÃ¡ acceso al sistema.":     {"en": "The user will regain system access."},
    "Activar":                                      {"en": "Activate"},
    "?? Activar":                                   {"en": "?? Activate"},
    "Cancelar":                                     {"en": "Cancel"},
    "? Cancelar":                                  {"en": "? Cancel"},

    # --------------------------------------------------------------
    # GESTIï¿½N DE FACULTADES ï¿½ tabla
    # --------------------------------------------------------------
    "?? GestiÃ³n de Facultades":                     {"en": "?? Faculty Management"},
    "??   GestiÃ³n de Facultades":                   {"en": "??   Faculty Management"},
    "Administra las unidades acadÃ©micas":           {"en": "Manage academic units"},
    "Administra las unidades acadÃ©micas del sistema": {"en": "Manage the system's academic units"},
    "Agregar Facultad":                             {"en": "Add Faculty"},
    "? Agregar Facultad":                          {"en": "? Add Faculty"},
    "Buscar facultad por nombre...":                {"en": "Search faculty by name..."},
    "No hay facultades registradas":                {"en": "No registered faculties"},
    "NOMBRE DE LA FACULTAD":                        {"en": "FACULTY NAME"},
    "ACTIVA":                                       {"en": "ACTIVE"},
    "INACTIVA":                                     {"en": "INACTIVE"},

    # GESTIï¿½N DE FACULTADES ï¿½ modal
    "ðŸ—‘ï¸Desactivar esta facultad?":                   {"en": "Desactivate this faculty?"},
    "La facultad dejarÃ¡ de estar disponible.":      {"en": "The faculty will no longer be available."},
    "Activar esta facultad?":                      {"en": "Activate this faculty?"},
    "La facultad volver a estar disponible.":      {"en": "The faculty will be available again."},

    # GESTIï¿½N DE FACULTADES ï¿½ formulario
    "Editar Facultad":                              {"en": "Edit Faculty"},
    "?? Editar Facultad":                           {"en": "?? Edit Faculty"},
    "Crear Nueva Facultad":                         {"en": "Create New Faculty"},
    "? Crear Nueva Facultad":                      {"en": "? Create New Faculty"},
    "Nombre de la Facultad":                        {"en": "Faculty Name"},
    "??? Nombre de la Facultad":                    {"en": "??? Faculty Name"},
    "Estado":                                       {"en": "Status"},
    "?? Estado":                                    {"en": "?? Status"},
    "Activa":                                       {"en": "Active"},
    "Inactiva":                                     {"en": "Inactive"},
    "Guardar Facultad":                             {"en": "Save Faculty"},
    "?? Guardar Facultad":                          {"en": "?? Save Faculty"},

    # --------------------------------------------------------------
    # GESTIï¿½N DE CARRERAS ï¿½ tabla
    # --------------------------------------------------------------
    "?? GestiÃ³n de Carreras":                       {"en": "?? Career Management"},
    "??   GestiÃ³n de Carreras":                     {"en": "??   Career Management"},
    "Agregar Carrera":                              {"en": "Add Career"},
    "? Agregar Carrera":                           {"en": "? Add Career"},
    "Buscar carrera por nombre...":                 {"en": "Search career by name..."},
    "No hay carreras registradas":                  {"en": "No registered careers"},
    "NOMBRE":                                       {"en": "NAME"},
    "FACULTAD":                                     {"en": "FACULTY"},

    # GESTIï¿½N DE CARRERAS ï¿½ modal
    "Desactivar esta carrera?":                    {"en": "Desactivate this career?"},
    "La carrera dejar de estar disponible.":       {"en": "The career will no longer be available."},
    "ðŸ”„Activar esta carrera?":                       {"en": "Activate this career?"},
    "La carrera volverÃ¡ a estar disponible.":       {"en": "The career will be available again."},

    # GESTIï¿½N DE CARRERAS ï¿½ formulario
    "Editar Carrera":                               {"en": "Edit Career"},
    "?? Editar Carrera":                            {"en": "?? Edit Career"},
    "Nueva Carrera":                                {"en": "New Career"},
    "? Nueva Carrera":                             {"en": "? New Career"},
    "Nombre de la Carrera":                         {"en": "Career Name"},
    "?? Nombre de la Carrera":                      {"en": "?? Career Name"},
    "Facultad":                                     {"en": "Faculty"},
    "?? Facultad":                                  {"en": "?? Faculty"},
    "Seleccionar facultad":                         {"en": "Select faculty"},
    "Guardar Carrera":                              {"en": "Save Career"},
    "?? Guardar Carrera":                           {"en": "?? Save Career"},

    # --------------------------------------------------------------
    # CUENTA / PERFIL
    # --------------------------------------------------------------
    "Configura tu perfil y preferencias":           {"en": "Configure your profile and preferences"},
    "Editar":                                       {"en": "Edit"},
    "Editar Perfil":                                {"en": "Edit Profile"},
    "?? Editar":                                    {"en": "?? Edit"},
    "?? Editar Perfil":                             {"en": "?? Edit Profile"},
    "Detalles de la Cuenta":                        {"en": "Account Details"},
    "?? Detalles de la Cuenta":                     {"en": "?? Account Details"},
    "Correo":                                       {"en": "Email"},
    "Telofono":                                     {"en": "Phone"},
    "?? Personalizacin":                           {"en": "?? Customization"},
    "PersonalizaciÃ³n":                              {"en": "Customization"},
    "Idioma del Sistema":                           {"en": "System Language"},
    "?? Idioma del Sistema":                        {"en": "?? System Language"},
    "ADMINISTRADOR DEL SISTEMA":                    {"en": "SYSTEM ADMINISTRATOR"},
    "??   Editar Registro":                         {"en": "??   Edit Record"},
    "Modifica tu informaciÃ³n personal":             {"en": "Modify your personal information"},
    "?? InformaciÃ³n Personal":                      {"en": "?? Personal Information"},
    "Guardar Cambios":                              {"en": "Save Changes"},
    "?? Guardar Cambios":                           {"en": "?? Save Changes"},
    "El nombre y correo son obligatorios.":         {"en": "Name and email are required."},
    "Cambios guardados correctamente.":             {"en": "Changes saved successfully."},
    "?? Actualizar Foto":                           {"en": "?? Update Photo"},
    "Actualizar Foto":                              {"en": "Update Photo"},
    "Editar Registro...":                           {"en": "Edit Record..."},

    # --------------------------------------------------------------
    # LOGIN
    # --------------------------------------------------------------
    "Sistema de Reconocimiento\nFacial":            {"en": "Facial Recognition\nSystem"},
    "Ingresa tus credenciales para continuar":      {"en": "Enter your credentials to continue"},
    "CORREO Ã“NICO":                           {"en": "EMAIL ADDRESS"},
    "Escribe tu correo":                            {"en": "Enter your email"},
    "CONTRASEÃ‘A":                                   {"en": "PASSWORD"},
    "Escribe tu contraseÃ±a":                        {"en": "Enter your password"},
    "INICIAR SESIÃ“N":                               {"en": "LOG IN"},
    "Credenciales incorrectas.":                    {"en": "Incorrect credentials."},

    # --------------------------------------------------------------
    # TERMINAL BIOMï¿½TRICA
    # --------------------------------------------------------------
    "?  RECONOCIMIENTO FACIAL  ?":                  {"en": "?  FACIAL RECOGNITION  ?"},
    "SISTEMA ACTIVO":                               {"en": "SYSTEM ACTIVE"},
    "ESPERANDO DETECCIÃ“N...":                       {"en": "WAITING FOR DETECTION..."},
    "LISTO":                                        {"en": "READY"},
    "Iniciando cÃ¡mara...":                          {"en": "Starting camera..."},
    "Sistema BiomÃ©trico v2.0":                      {"en": "Biometric System v2.0"},
    "Acceso Seguro":                                {"en": "Secure Access"},
    "Cifrado AES-256":                              {"en": "AES-256 Encryption"},

    # Terminal ï¿½ mensajes de detecciï¿½n y estado
    "ROSTRO DETECTADO":                             {"en": "FACE DETECTED"},
    "PROCESANDO...":                                {"en": "PROCESSING..."},
    "CAPTURANDO...":                                {"en": "CAPTURING..."},
    "CAPTURA EXITOSA":                              {"en": "CAPTURE SUCCESSFUL"},
    "IDENTIFICANDO...":                             {"en": "IDENTIFYING..."},
    "ACCESO AUTORIZADO":                            {"en": "ACCESS AUTHORIZED"},
    "ACCESO DENEGADO":                              {"en": "ACCESS DENIED"},
    "USUARIO INACTIVO":                             {"en": "INACTIVE USER"},
    "SIN DETECCIÃ“N":                                {"en": "NO DETECTION"},
    "CÃMARA NO DISPONIBLE":                         {"en": "CAMERA NOT AVAILABLE"},
    "ERROR DE CÃMARA":                              {"en": "CAMERA ERROR"},
    "CÃ¡mara no disponible":                         {"en": "Camera not available"},
    "Error al iniciar cÃ¡mara":                      {"en": "Error starting camera"},
    "BiometrÃ­a no encontrada":                      {"en": "Biometrics not found"},
    "REGISTRANDO ROSTRO":                           {"en": "REGISTERING FACE"},
    "REGISTRO EXITOSO":                             {"en": "REGISTRATION SUCCESSFUL"},
    "MANTÃ‰N EL ROSTRO EN EL CENTRO":               {"en": "KEEP YOUR FACE IN THE CENTER"},
    "ROSTRO MUY LEJOS":                             {"en": "FACE TOO FAR"},
    "ROSTRO MUY CERCA":                             {"en": "FACE TOO CLOSE"},
    "ILUMINACIÃ“N INSUFICIENTE":                     {"en": "INSUFFICIENT LIGHTING"},
    "Volver":                                       {"en": "Back"},
    "? Volver":                                     {"en": "? Back"},
    "CANCELAR":                                     {"en": "CANCEL"},

    # --------------------------------------------------------------
    # BOTONES COMUNES
    # --------------------------------------------------------------
    "Guardar":                                      {"en": "Save"},
    "?? Guardar":                                   {"en": "?? Save"},
    "Editar":                                       {"en": "Edit"},
    "?? Editar":                                    {"en": "?? Edit"},
    "Fecha:":                                       {"en": "Date:"},
}

TRADUCCIONES_UTF8 = {
    "Panel de Control": {"en": "Control Panel"},
    "GestiÃ³n de Usuarios": {"en": "User Management"},
    "Gestion de Usuarios": {"en": "User Management"},
    "GestiÃ³n de Facultades": {"en": "Faculty Management"},
    "Gestion de Facultades": {"en": "Faculty Management"},
    "GestiÃ³n de Carreras": {"en": "Career Management"},
    "Gestion de Carreras": {"en": "Career Management"},
    "ConfiguraciÃ³n": {"en": "Settings"},
    "ConfiguraciÃ³n Cuenta": {"en": "Account Settings"},
    "Cerrar SesiÃ³n": {"en": "Log Out"},
    "Control BiomÃ©trico": {"en": "Biometric Control"},
    "Resumen general y actividad reciente": {"en": "General overview and recent activity"},
    "Total Registros": {"en": "Total Records"},
    "Accesos Hoy": {"en": "Accesses Today"},
    "Autorizados": {"en": "Authorized"},
    "Denegados": {"en": "Denied"},
    "Tendencia de Accesos por Hora": {"en": "Access Trend by Hour"},
    "Fecha:": {"en": "Date:"},
    "Registro de Ãºltimos accesos": {"en": "Latest access log"},
    "Sin accesos registrados": {"en": "No access records found"},
    "Sin accesos registrados en esta fecha": {"en": "No access records for this date"},
    "Sin cuenta": {"en": "No account"},
    "Sin correo": {"en": "No email"},
    "Acceso autorizado": {"en": "Access authorized"},
    "Acceso denegado": {"en": "Access denied"},
    "AUTORIZADO": {"en": "AUTHORIZED"},
    "DENEGADO": {"en": "DENIED"},
    "USUARIO NO REGISTRADO": {"en": "UNREGISTERED USER"},
    "Agregar Usuario": {"en": "Add User"},
    "Buscar usuario...": {"en": "Search user..."},
    "No hay usuarios registrados": {"en": "No registered users"},
    "FOTOGRAFÃA": {"en": "PHOTOGRAPH"},
    "INFORMACIÃ“N": {"en": "INFORMATION"},
    "ESTADO": {"en": "STATUS"},
    "ACCIONES": {"en": "ACTIONS"},
    "Editar Registro": {"en": "Edit Record"},
    "Nuevo Registro": {"en": "New Record"},
    "ClasificaciÃ³n": {"en": "Classification"},
    "Tipo de Usuario": {"en": "User Type"},
    "InformaciÃ³n Personal": {"en": "Personal Information"},
    "IdentificaciÃ³n": {"en": "Identification"},
    "Estado del usuario": {"en": "User Status"},
    "Usuario activo": {"en": "Active user"},
    "Nombres": {"en": "First Name(s)"},
    "Apellido Paterno": {"en": "Paternal Last Name"},
    "Apellido Materno": {"en": "Maternal Last Name"},
    "cuenta": {"en": "account"},
    "correo": {"en": "email"},
    "Registrar BiometrÃ­a": {"en": "Register Biometrics"},
    "Guardar Usuario": {"en": "Save User"},
    "BiometrÃ­a requerida": {"en": "Biometrics required"},
    "BiometrÃ­a registrada": {"en": "Biometrics registered"},
    "Abriendo cÃ¡mara...": {"en": "Opening camera..."},
    "Corrige los datos primero": {"en": "Fix the data first"},
    "Â¿Desactivar este usuario?": {"en": "Deactivate this user?"},
    "El usuario perderÃ¡ acceso al sistema.": {"en": "The user will lose system access."},
    "Â¿Activar este usuario?": {"en": "Activate this user?"},
    "El usuario recuperarÃ¡ acceso al sistema.": {"en": "The user will regain system access."},
    "Rol:": {"en": "Role:"},
    "Todos": {"en": "All"},
    "Filtrar âŒµ": {"en": "Filter âŒµ"},
    "Filtrar ï¸¿": {"en": "Filter ï¸¿"},
    "Estudiante": {"en": "Student"},
    "Docente": {"en": "Teacher"},
    "Trabajador": {"en": "Worker"},
    "ESTUDIANTE": {"en": "STUDENT"},
    "DOCENTE": {"en": "TEACHER"},
    "TRABAJADOR": {"en": "WORKER"},
    "ACTIVO": {"en": "ACTIVE"},
    "INACTIVO": {"en": "INACTIVE"},
    "Administra las unidades acadÃ©micas": {"en": "Manage academic units"},
    "Administra las unidades acadÃ©micas del sistema": {"en": "Manage the system's academic units"},
    "Agregar Facultad": {"en": "Add Faculty"},
    "Buscar facultad por nombre...": {"en": "Search faculty by name..."},
    "No hay facultades registradas": {"en": "No registered faculties"},
    "NOMBRE DE LA FACULTAD": {"en": "FACULTY NAME"},
    "Editar Facultad": {"en": "Edit Faculty"},
    "Crear Nueva Facultad": {"en": "Create New Faculty"},
    "Nombre de la Facultad": {"en": "Faculty Name"},
    "Guardar Facultad": {"en": "Save Faculty"},
    "Â¿Desactivar esta facultad?": {"en": "Deactivate this faculty?"},
    "La facultad dejarÃ¡ de estar disponible.": {"en": "The faculty will no longer be available."},
    "Â¿Activar esta facultad?": {"en": "Activate this faculty?"},
    "La facultad volverÃ¡ a estar disponible.": {"en": "The faculty will be available again."},
    "Activa": {"en": "Active"},
    "Inactiva": {"en": "Inactive"},
    "ACTIVA": {"en": "ACTIVE"},
    "INACTIVA": {"en": "INACTIVE"},
    "Agregar Carrera": {"en": "Add Career"},
    "Buscar carrera por nombre...": {"en": "Search career by name..."},
    "No hay carreras registradas": {"en": "No registered careers"},
    "NOMBRE": {"en": "NAME"},
    "FACULTAD": {"en": "FACULTY"},
    "Editar Carrera": {"en": "Edit Career"},
    "Nueva Carrera": {"en": "New Career"},
    "Nombre de la Carrera": {"en": "Career Name"},
    "Facultad": {"en": "Faculty"},
    "Carrera": {"en": "Career"},
    "Seleccionar facultad": {"en": "Select faculty"},
    "Guardar Carrera": {"en": "Save Career"},
    "Â¿Desactivar esta carrera?": {"en": "Deactivate this career?"},
    "La carrera dejarÃ¡ de estar disponible.": {"en": "The career will no longer be available."},
    "Â¿Activar esta carrera?": {"en": "Activate this career?"},
    "La carrera volverÃ¡ a estar disponible.": {"en": "The career will be available again."},
    "Configura tu perfil y preferencias": {"en": "Configure your profile and preferences"},
    "Editar": {"en": "Edit"},
    "Editar Perfil": {"en": "Edit Profile"},
    "Detalles de la Cuenta": {"en": "Account Details"},
    "Correo": {"en": "Email"},
    "TelÃ©fono": {"en": "Phone"},
    "PersonalizaciÃ³n": {"en": "Customization"},
    "Idioma del Sistema": {"en": "System Language"},
    "ADMINISTRADOR DEL SISTEMA": {"en": "SYSTEM ADMINISTRATOR"},
    "Actualizar Foto": {"en": "Update Photo"},
    "Editar Registro...": {"en": "Edit Record..."},
    "Modifica tu informaciÃ³n personal": {"en": "Modify your personal information"},
    "Guardar Cambios": {"en": "Save Changes"},
    "El nombre y correo son obligatorios.": {"en": "Name and email are required."},
    "Cambios guardados correctamente.": {"en": "Changes saved successfully."},
    "Sistema de Reconocimiento\nFacial": {"en": "Facial Recognition\nSystem"},
    "Ingresa tus credenciales para continuar": {"en": "Enter your credentials to continue"},
    "CORREO ELECTRÃ“NICO": {"en": "EMAIL ADDRESS"},
    "Escribe tu correo": {"en": "Enter your email"},
    "CONTRASEÃ‘A": {"en": "PASSWORD"},
    "Escribe tu contraseÃ±a": {"en": "Enter your password"},
    "INICIAR SESIÃ“N": {"en": "LOG IN"},
    "Credenciales incorrectas.": {"en": "Incorrect credentials."},
    "Estado": {"en": "Status"},
    "Desactivar": {"en": "Deactivate"},
    "Activar": {"en": "Activate"},
    "Cancelar": {"en": "Cancel"},
    "Guardar": {"en": "Save"},
}

TRADUCCIONES.update(TRADUCCIONES_UTF8)

ALIAS_EMPRESA = {
    "Sistema de Reconocimiento\nFacial": "SECUREWORK\nControl de Acceso",
    "CORREO CORPORATIVO": "CORREO CORPORATIVO",
    "CONTRASENA": "CONTRASEÑA",
    "Escribe tu contrasena": "Escribe tu contraseña",
    "Sistema Biometrico v2.0": "BioAccess Empresarial v2.0",
    "RECONOCIMIENTO FACIAL": "CONTROL BIOMÉTRICO EMPRESARIAL",
    "CONTROL DE ACCESO": "CONTROL DE ACCESO",
    "Panel de Control": "Panel Ejecutivo",
    "Inicio": "Inicio",
    "Personal": "Personal",
    "Areas": "Áreas",
    "Nuevo trabajador": "Nuevo trabajador",
    "Áreas": "Áreas",
    "Puestos": "Puestos",
    "Nueva área": "Nueva área",
    "Nuevo puesto": "Nuevo puesto",
    "Ajustes": "Ajustes",
    "Perfil administrativo y preferencias del sistema": "Perfil administrativo y preferencias del sistema",
    "Resumen operativo de accesos, personal y alertas": "Resumen operativo de accesos, personal y alertas",
    "Personal activo": "Personal activo",
    "Eventos de hoy": "Eventos de hoy",
    "Accesos validos": "Accesos válidos",
    "Alertas": "Alertas",
    "Resumen general y actividad reciente": "Resumen de accesos y actividad laboral",
    "Total Registros": "Trabajadores Registrados",
    "Registro de Ãºltimos accesos": "Registro de últimos accesos",
    "ConfiguraciÃ³n": "Configuración",
    "Cerrar SesiÃ³n": "Cerrar Sesión",
    "FOTOGRAFÃA": "FOTOGRAFIA",
    "INFORMACIÃ“N": "INFORMACION",
    "PersonalizaciÃ³n": "Personalización",
    "TelÃ©fono": "Teléfono",
    "Modifica tu informaciÃ³n personal": "Modifica tu información personal",
    "GestiÃ³n de Usuarios": "Gestión de Trabajadores",
    "Gestion de Usuarios": "Gestión de Trabajadores",
    "Agregar Usuario": "Agregar Trabajador",
    "Buscar usuario...": "Buscar trabajador...",
    "Rol:": "Personal:",
    "cuenta": "Número de empleado",
    "correo": "Correo corporativo",
    "Tipo de Usuario": "Tipo de Personal",
    "Estado del usuario": "Estado del trabajador",
    "Usuario activo": "Trabajador activo",
    "IdentificaciÃ³n": "Identificación Laboral",
    "InformaciÃ³n Personal": "Información Personal",
    "ClasificaciÃ³n": "Clasificación Laboral",
    "Registrar BiometrÃ­a": "Registrar Biometría",
    "BiometrÃ­a requerida": "Biometría requerida",
    "No hay usuarios registrados": "No hay trabajadores registrados",
    "GestiÃ³n de Facultades": "Gestión de Áreas",
    "Gestion de Facultades": "Gestión de Áreas",
    "Agregar Facultad": "Agregar Área",
    "Nueva Facultad": "Nueva Área",
    "Nombre de la Facultad": "Nombre del Área",
    "NOMBRE DE LA FACULTAD": "NOMBRE DEL ÁREA",
    "Facultad": "Área de Trabajo",
    "FACULTAD": "ÁREA",
    "Seleccionar facultad": "Seleccionar área",
    "Buscar facultad por nombre...": "Buscar área por nombre...",
    "Administra las unidades acadÃ©micas": "Administra las áreas de trabajo",
    "Administra las unidades acadÃ©micas del sistema": "Administra las áreas operativas de la empresa",
    "No hay facultades registradas": "No hay áreas registradas",
    "GestiÃ³n de Carreras": "Gestión de Puestos",
    "Gestion de Carreras": "Gestión de Puestos",
    "Agregar Carrera": "Agregar Puesto",
    "Nueva Carrera": "Nuevo Puesto",
    "Nombre de la Carrera": "Nombre del Puesto",
    "Carrera": "Puesto",
    "CARRERA": "PUESTO",
    "Buscar carrera por nombre...": "Buscar puesto por nombre...",
    "No hay carreras registradas": "No hay puestos registrados",
    "La carrera dejarÃ¡ de estar disponible.": "El puesto dejará de estar disponible.",
    "La carrera volverÃ¡ a estar disponible.": "El puesto volverá a estar disponible.",
    "Â¿Desactivar esta carrera?": "¿Desactivar este puesto?",
    "Â¿Activar esta carrera?": "¿Activar este puesto?",
    "Editar Facultad": "Editar Área",
    "Crear Nueva Facultad": "Crear Nueva Área",
    "Guardar Facultad": "Guardar Área",
    "Â¿Desactivar esta facultad?": "¿Desactivar esta área?",
    "La facultad dejarÃ¡ de estar disponible.": "El área dejará de estar disponible.",
    "Â¿Activar esta facultad?": "¿Activar esta área?",
    "La facultad volverÃ¡ a estar disponible.": "El área volverá a estar disponible.",
    "Editar Carrera": "Editar Puesto",
    "Guardar Carrera": "Guardar Puesto",
    "Estudiante": "Trabajador",
    "Docente": "Supervisor",
    "Trabajador": "Administrativo",
    "ESTUDIANTE": "TRABAJADOR",
    "DOCENTE": "SUPERVISOR",
    "TRABAJADOR": "ADMINISTRATIVO",
    "Control BiomÃ©trico": "Control Empresarial",
    "ConfiguraciÃ³n Cuenta": "Configuración de Cuenta",
    "Configuracion Cuenta": "Configuración de Cuenta",
    "ADMINISTRADOR DEL SISTEMA": "ADMINISTRADOR EMPRESARIAL",
    "La cuenta es obligatoria": "El número de empleado es obligatorio",
    "La cuenta solo debe contener nÃºmeros": "El número de empleado solo debe contener números",
    "La cuenta ya estÃ¡ registrada": "El número de empleado ya está registrado",
    "Sin cuenta": "Sin número de empleado",
    "Filtrar âŒµ": "Filtrar",
    "Filtrar ï¸¿": "Filtrar",
    "Área": "Área",
    "Sin Correo corporativo": "Sin correo corporativo",
    "Sin área": "Sin área",
    "Sin puesto": "Sin puesto",
}

EMPRESA_EN = {
    "SECUREWORK\nControl de Acceso": "SECUREWORK\nAccess Control",
    "CORREO CORPORATIVO": "CORPORATE EMAIL",
    "CONTRASEÑA": "PASSWORD",
    "Escribe tu contraseña": "Enter your password",
    "BioAccess Empresarial v2.0": "BioAccess Enterprise v2.0",
    "CONTROL BIOMÉTRICO EMPRESARIAL": "ENTERPRISE BIOMETRIC CONTROL",
    "CONTROL DE ACCESO": "ACCESS CONTROL",
    "Panel Ejecutivo": "Executive Dashboard",
    "Inicio": "Home",
    "Personal": "Staff",
    "Nuevo trabajador": "New worker",
    "Áreas": "Areas",
    "Puestos": "Positions",
    "Nueva área": "New area",
    "Nuevo puesto": "New position",
    "Ajustes": "Settings",
    "Perfil administrativo y preferencias del sistema": "Administrator profile and system preferences",
    "Resumen operativo de accesos, personal y alertas": "Operational summary for access, staff, and alerts",
    "Personal activo": "Active staff",
    "Eventos de hoy": "Today events",
    "Accesos válidos": "Valid access",
    "Alertas": "Alerts",
    "Resumen de accesos y actividad laboral": "Access and workforce activity summary",
    "Trabajadores Registrados": "Registered Workers",
    "Registro de últimos accesos": "Latest access records",
    "Configuración": "Settings",
    "Cerrar Sesión": "Log Out",
    "FOTOGRAFIA": "PHOTO",
    "INFORMACION": "INFORMATION",
    "Personalización": "Customization",
    "Teléfono": "Phone",
    "Modifica tu información personal": "Edit your personal information",
    "Gestión de Trabajadores": "Worker Management",
    "Agregar Trabajador": "Add Worker",
    "Buscar trabajador...": "Search worker...",
    "Personal:": "Staff:",
    "Número de empleado": "Employee number",
    "Correo corporativo": "Corporate email",
    "Tipo de Personal": "Staff Type",
    "Estado del trabajador": "Worker status",
    "Trabajador activo": "Active worker",
    "Identificación Laboral": "Work Identification",
    "Información Personal": "Personal Information",
    "Clasificación Laboral": "Work Classification",
    "Registrar Biometría": "Register Biometrics",
    "Biometría requerida": "Biometrics required",
    "No hay trabajadores registrados": "No workers registered",
    "Gestión de Áreas": "Area Management",
    "Agregar Área": "Add Area",
    "Nueva Área": "New Area",
    "Nombre del Área": "Area Name",
    "NOMBRE DEL ÁREA": "AREA NAME",
    "Área de Trabajo": "Work Area",
    "ÁREA": "AREA",
    "Seleccionar área": "Select area",
    "Buscar área por nombre...": "Search area by name...",
    "Administra las áreas de trabajo": "Manage work areas",
    "Administra las áreas operativas de la empresa": "Manage the company's operating areas",
    "No hay áreas registradas": "No areas registered",
    "Gestión de Puestos": "Position Management",
    "Agregar Puesto": "Add Position",
    "Nuevo Puesto": "New Position",
    "Nombre del Puesto": "Position Name",
    "Puesto": "Position",
    "PUESTO": "POSITION",
    "Buscar puesto por nombre...": "Search position by name...",
    "No hay puestos registrados": "No positions registered",
    "El puesto dejará de estar disponible.": "The position will no longer be available.",
    "El puesto volverá a estar disponible.": "The position will be available again.",
    "¿Desactivar este puesto?": "Deactivate this position?",
    "¿Activar este puesto?": "Activate this position?",
    "Editar Área": "Edit Area",
    "Crear Nueva Área": "Create New Area",
    "Guardar Área": "Save Area",
    "¿Desactivar esta área?": "Deactivate this area?",
    "El área dejará de estar disponible.": "The area will no longer be available.",
    "¿Activar esta área?": "Activate this area?",
    "El área volverá a estar disponible.": "The area will be available again.",
    "Editar Puesto": "Edit Position",
    "Guardar Puesto": "Save Position",
    "Trabajador": "Worker",
    "Supervisor": "Supervisor",
    "Administrativo": "Administrative",
    "TRABAJADOR": "WORKER",
    "SUPERVISOR": "SUPERVISOR",
    "ADMINISTRATIVO": "ADMINISTRATIVE",
    "Control Empresarial": "Enterprise Control",
    "Configuración de Cuenta": "Account Settings",
    "ADMINISTRADOR EMPRESARIAL": "ENTERPRISE ADMINISTRATOR",
    "El número de empleado es obligatorio": "Employee number is required",
    "El número de empleado solo debe contener números": "Employee number must contain only digits",
    "El número de empleado ya está registrado": "Employee number is already registered",
    "Sin número de empleado": "No employee number",
    "Filtrar": "Filter",
    "Área": "Area",
    "Sin correo corporativo": "No corporate email",
    "Sin área": "No area",
    "Sin puesto": "No position",
    "Areas": "Areas",
    "Consola biometrica": "Biometric Console",
    "Panel": "Panel",
    "Entrar al panel": "Open panel",
    "Salir": "Exit",
    "Tablero operativo": "Operations Board",
    "Turno activo": "Active Shift",
    "Tasa de accesos autorizados hoy": "Authorized access rate today",
    "Eventos": "Events",
    "Validos": "Valid",
    "Radar horario": "Hourly Radar",
    "Fecha": "Date",
    "Actividad reciente": "Recent Activity",
    "Identidad administrativa": "Administrative Identity",
    "Perfil, contacto y sesion del operador": "Operator profile, contact, and session",
    "Editar perfil": "Edit profile",
    "Correo corporativo": "Corporate email",
    "Telefono": "Phone",
    "Area operativa": "Operational area",
    "Rol del sistema": "System role",
    "Sesion administrativa": "Administrative session",
    "Activa": "Active",
    "Operador con permisos de gestion y auditoria": "Operator with management and audit permissions",
    "Los cambios de perfil se reflejan en la barra superior del sistema.": "Profile changes appear in the system top bar.",
    "Editar identidad": "Edit identity",
    "Actualiza los datos visibles del operador": "Update the operator details shown in the app",
    "Foto y perfil": "Photo and profile",
    "La imagen se usara en la consola administrativa.": "This image will be used in the administrative console.",
    "Datos del operador": "Operator details",
    "Correo": "Email",
    "Nombre completo": "Full name",
    "10 digitos": "10 digits",
    "Nombre del area": "Area name",
}

class AppContext:
    idioma_actual = "es"
    traductor = None

    @classmethod
    def t(cls, texto: str) -> str:
        """Devuelve la traduccion del texto segun el idioma actual."""
        texto = str(texto)
        texto = ALIAS_EMPRESA.get(texto, texto)
        partes_alias = texto.strip().split(maxsplit=1)
        if len(partes_alias) == 2 and partes_alias[1] in ALIAS_EMPRESA:
            texto = f"{partes_alias[0]} {ALIAS_EMPRESA[partes_alias[1]]}"
        if cls.idioma_actual == "es":
            return texto

        clave = texto.strip()
        if clave in EMPRESA_EN:
            return EMPRESA_EN[clave]

        entrada = TRADUCCIONES.get(clave)
        if entrada:
            return entrada.get(cls.idioma_actual, clave)

        partes = clave.split(maxsplit=1)
        if len(partes) == 2 and not partes[0].replace("_", "").isalnum():
            icono, resto = partes
            entrada = TRADUCCIONES.get(resto)
            if entrada:
                return f"{icono} {entrada.get(cls.idioma_actual, resto)}"

        print(f"[i18n] Sin traduccion EN para: {repr(texto)}")
        return texto

    @classmethod
    def set_idioma(cls, nuevo_idioma: str) -> None:
        cls.idioma_actual = nuevo_idioma
